# GET SERVERS
GET https://api.treevpn.tech/apiv2/servers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZHZfaWQiOiIzN2IwODNjMi01MjUzLTRiZWYtODAxMi0wNmI4Y2JhYTEzMmIiLCJ1aWQiOjE5ODgzMCwiaWF0IjoxNjA1MDIyMDA3LCJleHAiOjE2MDUwMjU2MDcsImF1ZCI6IjM3YjA4M2MyLTUyNTMtNGJlZi04MDEyLTA2YjhjYmFhMTMyYiJ9.xGk7kCqO2MELEAycLit6oKk_whCh3q70gHKS9xviXo4

# OPENVPN LOGIN
POST https://api.treevpn.tech/apiv2/auth/login
content-Type: application/json

{
    "adv_id": "37b083c2-5253-4bef-8012-06b8cbaa132b",
    "password": "5715621372d886ef4d9c60a462517921bf0bf1a90e844e9c28c2c72003d177cb"
}


# # Refresh token
# # POST https://api.treevpn.tech/apiv2/auth/refresh-token
# # content-Type: application/json

# # {
# #     "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE5ODA1OSwiYWR2X2lkIjoiYjgzOTY2ODctMGJmZC00ZjcyLTljOTItZGRjNWFiZjViZDU0IiwiaWF0IjoxNjA0Mzk1NTEzLCJleHAiOjE2MDQzOTU1NDMsImF1ZCI6ImI4Mzk2Njg3LTBiZmQtNGY3Mi05YzkyLWRkYzVhYmY1YmQ1NCJ9._8BptFhSbV2BLeHWKnjU7KbHLseRN-lcqoFViiIty2w"
# # }

# ### Login route
# POST https://api.treevpn.tech/apiv2/auth/login
# content-Type: application/json

# {
#     "adv_id": "37b083c2-5253-4bef-8012-06b8cbaa132b",
#     "password": "5715621372d886ef4d9c60a462517921bf0bf1a90e844e9c28c2c72003d177cb"
# }

# # ### POSTBACK ROUTE
# # GET https://api.treevpn.tech/apiv2/postback
# # Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE5ODQwOCwiYWR2X2lkIjoiYjgzOTY2ODctMGJmZC00ZjcyLTljOTItZGRjNWFiZjViZDU0IiwiaWF0IjoxNjA0Mzk4MTkwLCJleHAiOjE2MDQ0MDE3OTAsImF1ZCI6ImI4Mzk2Njg3LTBiZmQtNGY3Mi05YzkyLWRkYzVhYmY1YmQ1NCJ9.DB3CsmhOg7O3zMiDOv86C1YQdWyVlRqlTXOerKh_8nc

# # ### UPDATE REFERER
# POST https://api.treevpn.tech/apiv2/servers
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE5ODQwOCwiYWR2X2lkIjoiYjgzOTY2ODctMGJmZC00ZjcyLTljOTItZGRjNWFiZjViZDU0IiwiaWF0IjoxNjA0Mzk4MTkwLCJleHAiOjE2MDQ0MDE3OTAsImF1ZCI6ImI4Mzk2Njg3LTBiZmQtNGY3Mi05YzkyLWRkYzVhYmY1YmQ1NCJ9.DB3CsmhOg7O3zMiDOv86C1YQdWyVlRqlTXOerKh_8nc
# content-Type: application/json

# {
#     "referer": "test-referer"
# }

